### ISSUE TITLE
 panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by xabru** [stefanprodan/dockprom#218] opened 2021-03-20 02:32 UTC
![image](https://user-images.githubusercontent.com/55867760/111856648-3659fa00-88fa-11eb-8904-d5b913daedbd.png)

![image](https://user-images.githubusercontent.com/55867760/111856707-9781cd80-88fa-11eb-888a-044d632907cc.png)

❯ docker-compose ps
    Name                  Command                       State            Ports
--------------------------------------------------------------------------------
alertmanager   /bin/alertmanager --config ...   Up                      9093/tcp
caddy          /sbin/tini -- caddy -agree ...   Restarting
cadvisor       /usr/bin/cadvisor -logtostderr   Up (health: starting)   8080/tcp
grafana        /run.sh                          Up                      3000/tcp
nodeexporter   /bin/node_exporter --path. ...   Up                      9100/tcp
prometheus     /bin/prometheus --config.f ...   Up                      9090/tcp
pushgateway    /bin/pushgateway                 Up                      9091/tcp

`❯ docker-compose logs caddy
Attaching to caddy
caddy           | panic: runtime error: slice bounds out of range
caddy           |
caddy           | goroutine 1 [running]:
caddy           | github.com/mholt/caddy/vendor/github.com/miekg/dns.ClientConfigFromFile(0xbb4739, 0x10, 0x0, 0x0, 0x0)
caddy           |       src/github.com/mholt/caddy/vendor/github.com/miekg/dns/clientconfig.go:86 +0xad6
caddy           | github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme.getNameservers(0xbb4739, 0x10, 0xfeaf20, 0x2, 0x2, 0xf77460, 0xc4200402c0, 0xc420037f50)
caddy           |       src/github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme/dns_challenge.go:40 +0x4d
caddy           | github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme.init()
caddy           |       src/github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme/dns_challenge.go:33 +0x12d
caddy           | github.com/mholt/caddy/caddy/caddymain.init()
caddy           |       <autogenerated>:1 +0x75
caddy           | main.init()
caddy           |       <autogenerated>:1 +0x44
caddy           | panic: runtime error: slice bounds out of range
caddy           |
caddy           | goroutine 1 [running]:
caddy           | github.com/mholt/caddy/vendor/github.com/miekg/dns.ClientConfigFromFile(0xbb4739, 0x10, 0x0, 0x0, 0x0)
caddy           |       src/github.com/mholt/caddy/vendor/github.com/miekg/dns/clientconfig.go:86 +0xad6
caddy           | github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme.getNameservers(0xbb4739, 0x10, 0xfeaf20, 0x2, 0x2, 0xf77460, 0xc42005c2b0, 0xc420037f50)
caddy           |       src/github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme/dns_challenge.go:40 +0x4d
caddy           | github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme.init()
caddy           |       src/github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme/dns_challenge.go:33 +0x12d
caddy           | github.com/mholt/caddy/caddy/caddymain.init()
caddy           |       <autogenerated>:1 +0x75
caddy           | main.init()
caddy           |       <autogenerated>:1 +0x44
caddy           | panic: runtime error: slice bounds out of range
caddy           |
caddy           | goroutine 1 [running]:
caddy           | github.com/mholt/caddy/vendor/github.com/miekg/dns.ClientConfigFromFile(0xbb4739, 0x10, 0x0, 0x0, 0x0)
caddy           |       src/github.com/mholt/caddy/vendor/github.com/miekg/dns/clientconfig.go:86 +0xad6
caddy           | github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme.getNameservers(0xbb4739, 0x10, 0xfeaf20, 0x2, 0x2, 0xf77460, 0xc4200402c0, 0xc420037f50)
caddy           |       src/github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme/dns_challenge.go:40 +0x4d
caddy           | github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme.init()
caddy           |       src/github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme/dns_challenge.go:33 +0x12d
caddy           | github.com/mholt/caddy/caddy/caddymain.init()
caddy           |       <autogenerated>:1 +0x75
caddy           | main.init()
caddy           |       <autogenerated>:1 +0x44
caddy           | panic: runtime error: slice bounds out of range
caddy           |
caddy           | goroutine 1 [running]:
caddy           | github.com/mholt/caddy/vendor/github.com/miekg/dns.ClientConfigFromFile(0xbb4739, 0x10, 0x0, 0x0, 0x0)
caddy           |       src/github.com/mholt/caddy/vendor/github.com/miekg/dns/clientconfig.go:86 +0xad6
caddy           | github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme.getNameservers(0xbb4739, 0x10, 0xfeaf20, 0x2, 0x2, 0xf77460, 0xc4200402c0, 0xc420037f50)
caddy           |       src/github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme/dns_challenge.go:40 +0x4d
caddy           | github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme.init()
caddy           |       src/github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme/dns_challenge.go:33 +0x12d
caddy           | github.com/mholt/caddy/caddy/caddymain.init()
caddy           |       <autogenerated>:1 +0x75
caddy           | main.init()
caddy           |       <autogenerated>:1 +0x44
caddy           | panic: runtime error: slice bounds out of range
caddy           |
caddy           | goroutine 1 [running]:
caddy           | github.com/mholt/caddy/vendor/github.com/miekg/dns.ClientConfigFromFile(0xbb4739, 0x10, 0x0, 0x0, 0x0)
caddy           |       src/github.com/mholt/caddy/vendor/github.com/miekg/dns/clientconfig.go:86 +0xad6
caddy           | github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme.getNameservers(0xbb4739, 0x10, 0xfeaf20, 0x2, 0x2, 0xf77460, 0xc4200402c0, 0xc420037f50)
caddy           |       src/github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme/dns_challenge.go:40 +0x4d
caddy           | github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme.init()
caddy           |       src/github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme/dns_challenge.go:33 +0x12d
caddy           | github.com/mholt/caddy/caddy/caddymain.init()
caddy           |       <autogenerated>:1 +0x75
caddy           | main.init()
caddy           |       <autogenerated>:1 +0x44
caddy           | panic: runtime error: slice bounds out of range
caddy           |
caddy           | goroutine 1 [running]:
caddy           | github.com/mholt/caddy/vendor/github.com/miekg/dns.ClientConfigFromFile(0xbb4739, 0x10, 0x0, 0x0, 0x0)
caddy           |       src/github.com/mholt/caddy/vendor/github.com/miekg/dns/clientconfig.go:86 +0xad6
caddy           | github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme.getNameservers(0xbb4739, 0x10, 0xfeaf20, 0x2, 0x2, 0xf77460, 0xc4200402c0, 0xc420037f50)
caddy           |       src/github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme/dns_challenge.go:40 +0x4d
caddy           | github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme.init()
caddy           |       src/github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme/dns_challenge.go:33 +0x12d
caddy           | github.com/mholt/caddy/caddy/caddymain.init()
caddy           |       <autogenerated>:1 +0x75
caddy           | main.init()
caddy           |       <autogenerated>:1 +0x44
caddy           | panic: runtime error: slice bounds out of range
caddy           |
caddy           | goroutine 1 [running]:
caddy           | github.com/mholt/caddy/vendor/github.com/miekg/dns.ClientConfigFromFile(0xbb4739, 0x10, 0x0, 0x0, 0x0)
caddy           |       src/github.com/mholt/caddy/vendor/github.com/miekg/dns/clientconfig.go:86 +0xad6
caddy           | github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme.getNameservers(0xbb4739, 0x10, 0xfeaf20, 0x2, 0x2, 0xf77460, 0xc4200402c0, 0xc420037f50)
caddy           |       src/github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme/dns_challenge.go:40 +0x4d
caddy           | github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme.init()
caddy           |       src/github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme/dns_challenge.go:33 +0x12d
caddy           | github.com/mholt/caddy/caddy/caddymain.init()
caddy           |       <autogenerated>:1 +0x75
caddy           | main.init()
caddy           |       <autogenerated>:1 +0x44
caddy           | panic: runtime error: slice bounds out of range
caddy           |
caddy           | goroutine 1 [running]:
caddy           | github.com/mholt/caddy/vendor/github.com/miekg/dns.ClientConfigFromFile(0xbb4739, 0x10, 0x0, 0x0, 0x0)
caddy           |       src/github.com/mholt/caddy/vendor/github.com/miekg/dns/clientconfig.go:86 +0xad6
caddy           | github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme.getNameservers(0xbb4739, 0x10, 0xfeaf20, 0x2, 0x2, 0xf77460, 0xc4200402c0, 0xc420037f50)
caddy           |       src/github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme/dns_challenge.go:40 +0x4d
caddy           | github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme.init()
caddy           |       src/github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme/dns_challenge.go:33 +0x12d
caddy           | github.com/mholt/caddy/caddy/caddymain.init()
caddy           |       <autogenerated>:1 +0x75
caddy           | main.init()
caddy           |       <autogenerated>:1 +0x44`

**Comment by arthur-lbchn** [comment] 2021-03-20 18:46
I have the same issue while trying this build:

![Screenshot_129](https://user-images.githubusercontent.com/9682681/111882242-471f7400-89bd-11eb-9175-aef7b505bdf3.png)

**Comment by nightah** [comment] 2021-03-28 00:31
The issue is specifically related to a default configuration with Ubuntu and Caddy v1.

This has been resolved in [v3.30.0](https://github.com/stefanprodan/dockprom/releases/tag/v3.30.0).

**Closed by nightah** 2021-03-28 00:31 UTC
