### ISSUE TITLE
Swarm mode?

### ISSUE THREAD

**Issue by stationcasinosgithub** [stefanprodan/dockprom#3] opened 2016-10-18 00:12 UTC
This is a great combination for monitoring our Docker environment.  However we are trying to get swarm mode services to show without any luck.  Any suggestions?

Thanks!

**Comment by stefanprodan** [comment] 2016-10-18 07:53
duplicate of #1

**Comment by phuthinh2202** [comment] 2017-04-04 03:21
Here is the link to my blog that talk about how to build prometheus running on Swarm mode. I extended from stefanprodan/dockprom. [lazyadmin.info](http://lazyadmin.info/python/how-to-setup-prometheus-and-grafana-running-on-docker-swarm-mode-post21)

**Comment by stefanprodan** [comment] 2017-10-16 09:46
The Docker Swarm version can be found at https://github.com/stefanprodan/swarmprom

**Comment by nightah** [comment] 2018-12-03 06:39
@stationcasinosgithub, I'm closing this issue off as an alternative to monitor your swarm services has been provided.
If you have an issue which relates to this repo and not the swarmprom variant please open another issue.

**Closed by nightah** 2018-12-03 06:39 UTC
